// @ts-ignore
import { X, Plus, Minus, Trash2 } from "lucide-react";
import React, { useState } from "react";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import { Textarea } from "../../ui/textarea";
import { Select } from "../../ui/select";
import { Card } from "../../ui/card";
import { Badge } from "../../ui/badge";
import { Invoice, Product, User, CartItem } from "../../../types";
import {
  createInvoice,
  createOrUpdateUserInFirestore,
} from "../../../services/firestore-service";
import { toast } from "sonner";
import { CustomerSelectModal } from "./CustomerSelectModal";
import { InvoicePrintModal } from "./InvoicePrintModal";

interface CreateInvoiceFormProps {
  products: Product[];
  customers: User[];
  onSuccess: () => void;
  onCancel: () => void;
}

export function CreateInvoiceForm({
  products,
  customers,
  onSuccess,
  onCancel,
}: CreateInvoiceFormProps) {
  const [selectedCustomer, setSelectedCustomer] = useState<User | null>(null);
  const [showCustomerModal, setShowCustomerModal] = useState(false);
  const [invoiceItems, setInvoiceItems] = useState<CartItem[]>([]);
  const [taxRate, setTaxRate] = useState<number>(0);
  const [discount, setDiscount] = useState<number>(0);
  const [paymentMethod, setPaymentMethod] = useState<
    "card" | "upi" | "cheque" | "bank-transfer"
  >("card");
  const [paymentStatus, setPaymentStatus] = useState<
    "paid" | "pending" | "partial"
  >("paid");
  const [notes, setNotes] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const [showPrintModal, setShowPrintModal] = useState(false);
  const [createdInvoiceData, setCreatedInvoiceData] = useState<any>(null);

  const paymentMethods = [
    { value: "card", label: "Card" },
    { value: "upi", label: "UPI" },
    { value: "cheque", label: "Cheque" },
    { value: "bank-transfer", label: "Bank Transfer" },
  ];

  const paymentStatuses = [
    { value: "paid", label: "Paid" },
    { value: "pending", label: "Pending" },
    { value: "partial", label: "Partial" },
  ];

  const calculateSubtotal = () => {
    return invoiceItems.reduce((sum, item) => {
      const price =
        selectedCustomer?.role === "reseller"
          ? item.product.resellerPrice
          : item.product.retailPrice;
      return sum + price * item.quantity;
    }, 0);
  };

  const subtotal = calculateSubtotal();
  const taxAmount = (subtotal * taxRate) / 100;
  const discountAmount = discount || 0;
  const total = subtotal + taxAmount - discountAmount;

  const handleAddProduct = (product: Product) => {
    const existingItem = invoiceItems.find(
      (item) => item.product.id === product.id,
    );
    if (existingItem) {
      setInvoiceItems(
        invoiceItems.map((item) =>
          item.product.id === product.id
            ? { ...item, quantity: Math.min(item.quantity + 1, product.stock) }
            : item,
        ),
      );
    } else {
      setInvoiceItems([...invoiceItems, { product, quantity: 1 }]);
    }
  };

  const handleUpdateQuantity = (productId: string, quantity: number): void => {
    const product = invoiceItems.find(
      (item) => item.product.id === productId,
    )?.product;
    if (product && quantity > 0 && quantity <= product.stock) {
      setInvoiceItems(
        invoiceItems.map((item) =>
          item.product.id === productId ? { ...item, quantity } : item,
        ),
      );
    }
  };

  const handleRemoveItem = (productId: string): void => {
    setInvoiceItems(
      invoiceItems.filter((item) => item.product.id !== productId),
    );
  };

  const handleCreateInvoice = async () => {
    if (!selectedCustomer) {
      toast.error("Please select a customer");
      return;
    }

    if (invoiceItems.length === 0) {
      toast.error("Please add at least one product to the invoice");
      return;
    }

    setIsCreating(true);
    try {
      const invoiceData: Omit<Invoice, "id"> = {
        invoiceNumber: "", // Will be generated by service
        customerId: selectedCustomer.id,
        customerName: selectedCustomer.name,
        customerEmail: selectedCustomer.email,
        customerPhone: selectedCustomer.phone || "",
        customerAddress: selectedCustomer.addresses?.[0]?.addressLine1 || "",
        items: invoiceItems,
        subtotal,
        tax: taxAmount,
        discount: discountAmount,
        total,
        paymentMethod,
        paymentStatus,
        notes,
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      const result = await createInvoice(invoiceData);

      // Store invoice data for print modal
      const printData = {
        ...invoiceData,
        id: result,
        invoiceNumber: invoiceData.invoiceNumber || result || "draft",
        paidAmount: paymentStatus === "paid" ? total : 0,
      };

      setCreatedInvoiceData(printData);
      setShowPrintModal(true);
      toast.success("Invoice created successfully!");
    } catch (error) {
      console.error("Error creating invoice:", error);
      toast.error("Failed to create invoice");
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      {/* Left Column - Main Content */}
      <div className="lg:col-span-2 space-y-6">
        {/* Customer Selection Card */}
        <Card className="p-6 border-slate-200 shadow-sm hover:shadow-md transition-shadow">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold text-slate-800">
                Customer Info
              </h3>
              <Badge variant={selectedCustomer ? "default" : "info"}>
                {selectedCustomer?.role === "reseller"
                  ? "Reseller"
                  : "Customer"}
              </Badge>
            </div>

            {selectedCustomer ? (
              <div className="p-4 bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg border border-blue-200">
                <p className="text-sm text-slate-600 mb-1">Selected Customer</p>
                <p className="font-semibold text-slate-900 text-lg">
                  {selectedCustomer.name}
                </p>
                <div className="mt-3 space-y-1 text-sm text-slate-700">
                  <p>Phone: {selectedCustomer.phone}</p>
                  {selectedCustomer.email && (
                    <p>Email: {selectedCustomer.email}</p>
                  )}
                </div>
              </div>
            ) : (
              <div className="p-4 bg-red-50 rounded-lg border-2 border-dashed border-red-200">
                <p className="text-sm font-medium text-red-700">
                  ⚠ No customer selected yet
                </p>
              </div>
            )}

            <Button
              type="button"
              variant="outline"
              className="w-full"
              onClick={() => setShowCustomerModal(true)}
            >
              {selectedCustomer ? "Change Customer" : "Select Customer"}
            </Button>
          </div>
        </Card>

        {/* Products Section */}
        <Card className="p-6 border-slate-200 shadow-sm hover:shadow-md transition-shadow">
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-slate-800">
              Available Products
            </h3>
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 max-h-80 overflow-y-auto">
              <div className="space-y-2">
                {products.length === 0 ? (
                  <p className="text-center text-slate-500 text-sm py-8">
                    No products available
                  </p>
                ) : (
                  products.map((product) => (
                    <div
                      key={product.id}
                      className="flex items-center justify-between p-3 bg-white hover:bg-blue-50 rounded-lg border border-slate-200 hover:border-blue-300 transition-all"
                    >
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-800">
                          {product.name}
                        </p>
                        <div className="flex items-center gap-2 mt-1">
                          <span className="text-xs font-semibold text-blue-600">
                            ₹
                            {(selectedCustomer?.role === "reseller"
                              ? product.resellerPrice
                              : product.retailPrice
                            ).toLocaleString()}
                          </span>
                          <span className="text-xs text-slate-500">
                            Stock: {product.stock}
                          </span>
                        </div>
                      </div>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => handleAddProduct(product)}
                        disabled={product.stock === 0}
                        className="ml-2"
                      >
                        {/* @ts-ignore */}
                        <Plus width={16} height={16} />
                      </Button>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </Card>

        {/* Invoice Items Table */}
        {invoiceItems.length > 0 && (
          <Card className="p-6 border-slate-200 shadow-sm hover:shadow-md transition-shadow">
            <div className="space-y-4">
              <h3 className="text-lg font-semibold text-slate-800">
                Invoice Items ({invoiceItems.length})
              </h3>
              <div className="overflow-x-auto rounded-lg border border-slate-200">
                <table className="w-full text-sm">
                  <thead className="bg-gradient-to-r from-slate-100 to-slate-50 border-b">
                    <tr>
                      <th className="px-4 py-3 text-left font-semibold text-slate-700">
                        Product
                      </th>
                      <th className="px-3 py-3 text-center font-semibold text-slate-700">
                        Price
                      </th>
                      <th className="px-3 py-3 text-center font-semibold text-slate-700">
                        Qty
                      </th>
                      <th className="px-3 py-3 text-center font-semibold text-slate-700">
                        Total
                      </th>
                      <th className="px-3 py-3 text-center font-semibold text-slate-700">
                        Action
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {invoiceItems.map((item) => (
                      <tr
                        key={item.product.id}
                        className="border-b hover:bg-blue-50 transition-colors"
                      >
                        <td className="px-4 py-3">
                          <p className="font-medium text-slate-800">
                            {item.product.name}
                          </p>
                          <p className="text-xs text-slate-500">
                            SKU: {item.product.sku}
                          </p>
                        </td>
                        <td className="px-3 py-3 text-center font-medium text-slate-700">
                          ₹
                          {(selectedCustomer?.role === "reseller"
                            ? item.product.resellerPrice
                            : item.product.retailPrice
                          ).toLocaleString()}
                        </td>
                        <td className="px-3 py-3">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() =>
                                handleUpdateQuantity(
                                  item.product.id,
                                  item.quantity - 1,
                                )
                              }
                              className="p-1 hover:bg-slate-300 rounded-md transition-colors"
                            >
                              <Minus width={14} height={14} />
                            </button>
                            <span className="w-8 text-center font-semibold text-slate-800">
                              {item.quantity}
                            </span>
                            <button
                              onClick={() =>
                                handleUpdateQuantity(
                                  item.product.id,
                                  item.quantity + 1,
                                )
                              }
                              className="p-1 hover:bg-slate-300 rounded-md transition-colors"
                            >
                              <Plus width={14} height={14} />
                            </button>
                          </div>
                        </td>
                        <td className="px-3 py-3 text-center font-bold text-blue-600 text-sm">
                          ₹
                          {(
                            (selectedCustomer?.role === "reseller"
                              ? item.product.resellerPrice
                              : item.product.retailPrice) * item.quantity
                          ).toLocaleString()}
                        </td>
                        <td className="px-3 py-3 text-center">
                          <button
                            onClick={() => handleRemoveItem(item.product.id)}
                            className="p-2 hover:bg-red-50 rounded-md text-red-600 transition-colors"
                          >
                            <Trash2 width={16} height={16} />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </Card>
        )}
      </div>

      {/* Right Column - Summary & Payment */}
      <div className="space-y-6">
        {/* Summary Card */}
        <Card className="p-6 bg-gradient-to-br from-slate-50 via-white to-blue-50 border-slate-200 shadow-sm">
          <div className="space-y-5">
            <h3 className="text-lg font-semibold text-slate-800">
              Order Summary
            </h3>

            {/* Subtotal */}
            <div className="flex justify-between items-center pt-2 border-t border-slate-200">
              <span className="text-slate-600 text-sm">Subtotal</span>
              <span className="font-semibold text-slate-800">
                ₹{subtotal.toLocaleString()}
              </span>
            </div>

            {/* Tax Section */}
            <div className="space-y-3 pt-2">
              <label className="text-sm font-medium text-slate-700 block">
                Tax Rate (%)
              </label>
              <Input
                type="number"
                min="0"
                max="100"
                step="0.5"
                value={taxRate}
                onChange={(e) => setTaxRate(parseFloat(e.target.value) || 0)}
                placeholder="0"
                className="h-9 text-sm"
              />
              <div className="flex justify-between items-center">
                <span className="text-xs text-slate-600">Tax Amount</span>
                <span className="font-semibold text-slate-800 text-sm">
                  ₹{taxAmount.toLocaleString()}
                </span>
              </div>
            </div>

            {/* Discount Section */}
            <div className="space-y-3 pt-2">
              <label className="text-sm font-medium text-slate-700 block">
                Discount (₹)
              </label>
              <Input
                type="number"
                min="0"
                value={discount}
                onChange={(e) => setDiscount(parseFloat(e.target.value) || 0)}
                placeholder="0"
                className="h-9 text-sm"
              />
              <div className="flex justify-between items-center">
                <span className="text-xs text-slate-600">After Discount</span>
                <span className="font-semibold text-slate-800 text-sm">
                  ₹{(subtotal + taxAmount - discountAmount).toLocaleString()}
                </span>
              </div>
            </div>

            {/* Total */}
            <div className="bg-gradient-to-r from-blue-500 to-blue-600 rounded-lg p-4 mt-4">
              <div className="flex justify-between items-center">
                <span className="font-semibold text-white">Total Amount</span>
                <span className="font-bold text-white text-2xl">
                  ₹{total.toLocaleString()}
                </span>
              </div>
            </div>
          </div>
        </Card>

        {/* Payment Details Card */}
        <Card className="p-6 border-slate-200 shadow-sm hover:shadow-md transition-shadow">
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-slate-800">
              Payment Info
            </h3>

            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700">
                Payment Method
              </label>
              <select
                value={paymentMethod}
                onChange={(e) =>
                  setPaymentMethod(e.target.value as typeof paymentMethod)
                }
                className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white"
              >
                {paymentMethods.map((method) => (
                  <option key={method.value} value={method.value}>
                    {method.label}
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium text-slate-700">
                Payment Status
              </label>
              <select
                value={paymentStatus}
                onChange={(e) =>
                  setPaymentStatus(e.target.value as typeof paymentStatus)
                }
                className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white"
              >
                {paymentStatuses.map((status) => (
                  <option key={status.value} value={status.value}>
                    {status.label}
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-2 pt-2">
              <label className="text-sm font-medium text-slate-700">
                Notes
              </label>
              <Textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="Add notes or special instructions..."
                rows={3}
                className="text-sm resize-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>
          </div>
        </Card>

        {/* Action Buttons */}
        <div className="space-y-3 pt-2">
          <Button
            type="button"
            variant="primary"
            className="w-full py-6 text-base font-semibold"
            onClick={handleCreateInvoice}
            disabled={
              isCreating || !selectedCustomer || invoiceItems.length === 0
            }
          >
            {isCreating ? (
              <span className="flex items-center gap-2">
                <span className="animate-spin">⏳</span>
                Creating Invoice...
              </span>
            ) : (
              "Create Invoice"
            )}
          </Button>
          <Button
            type="button"
            variant="outline"
            className="w-full py-2 text-sm"
            onClick={onCancel}
            disabled={isCreating}
          >
            Cancel
          </Button>
        </div>
      </div>

      {/* Customer Modal */}
      <CustomerSelectModal
        isOpen={showCustomerModal}
        customers={customers}
        onSelect={(customer: User) => {
          setSelectedCustomer(customer);
          setShowCustomerModal(false);
        }}
        onClose={() => setShowCustomerModal(false)}
        onCreateNew={(newCustomer: User) => {
          setSelectedCustomer(newCustomer);
          setShowCustomerModal(false);
        }}
      />

      {/* Print Invoice Modal */}
      <InvoicePrintModal
        isOpen={showPrintModal}
        invoiceData={createdInvoiceData}
        onClose={() => {
          setShowPrintModal(false);
          onSuccess();
        }}
      />
    </div>
  );
}
